# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-02 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('insumo', models.CharField(choices=[('RFCO', 'Refrescos'), ('PPS', 'Papas'), ('TST', 'Tostadas'), ('VS', 'Vasos'), ('PL', 'Platos')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Posada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='asistente',
            name='posada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistentes', to='posadas.Posada'),
        ),
    ]
